service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs: # Add the outputs to AWS CloudFormation Outputs tab
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events: # SQS to trigger the lambda function
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1 # process 1 email at a time from SQS message que

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage} # eq to "MailQueue-dev"
    arn: !GetAtt MailQueue.Arn # arn is provided by !GetAtt intrinsic function, MailQueue is logic name
    url: !Ref MailQueue # Ref returns the queue URL
